### ISSUE TITLE
Extended OrderItem model and List All Promotion Tiers methods

### ISSUE THREAD

**Issue by bandraszyk** [voucherifyio/voucherify-ios-sdk#19]
Make sure that the following methods are provided:

- Server side: Promotions.ListAllTiers(?is_avai=able=true/false); https://docs.voucherify.io/v2018-08-01/reference#list-promotion-tiers
- Client side: Promotions.ListAllTiers(?is_avai=able=true/false); https://docs.voucherify.io/v2018-08-01/reference#list-promotion-tiers-client-side 

Make sure that the following methods can work with extended Order Item model:

- Order; https://docs.voucherify.io/v2018-08-01/reference#the-order-object
- Order Items; https://docs.voucherify.io/v2018-08-01/reference#the-order-item-object\

- Create Order; https://docs.voucherify.io/v2018-08-01/reference#create-order
- Update Order; https://docs.voucherify.io/v2018-08-01/reference#update-order
- Validate Voucher; https://docs.voucherify.io/v2018-08-01/reference#validate-voucher
- Validate Voucher (client side); https://docs.voucherify.io/v2018-08-01/reference#vouchers-validate
- Validate Promotions; https://docs.voucherify.io/v2018-08-01/reference#validate-promotions-1
- Redeem Voucher; https://docs.voucherify.io/v2018-08-01/reference#redeem-voucher
- Redeem Voucher (client side); https://docs.voucherify.io/v2018-08-01/reference#redeem-voucher-client-side
- Redeem Promotion; https://docs.voucherify.io/v2018-08-01/reference#redeem-promotion

Close the issue if no operation is needed or provide a solution with next release.

**Comment by polok** [comment]
New release is coming: https://github.com/voucherifyio/voucherify-ios-sdk/pull/20

**Comment by polok** [comment]
Done, v3.3.0 has been just released
