### ISSUE TITLE
Problem with weak reference

### ISSUE THREAD

**Issue by glancashire** [voucherifyio/voucherify-ios-sdk#25]
Dear Voucherifiers,

I hit a problem when upgrading the most recent Swift SDK. With the old one it works fine.

When I validate vouchers with the new SDK it works fine, but when I try to redeem afterwards I hit an issues in VoucherifyRedemption.swift, in the function redeem.

In your code the [weak self] (response) causes the "guard let strongSelf = self else {return} to always return.

When I remove the weak it works perfectly.

This seems to be a common problem when using Alamofire:
https://stackoverflow.com/questions/49004074/weak-self-always-nil-in-asynchronous-closure-alamofire?rq=1

Thanks for your help.

Kind Regards
Graham

**Comment by polok** [comment]
@glancashire Thanks for pointing this out. We gonna dive into this deeper and will back to you. 

Also, you validate a voucher and then in completion block you send a redem request or you are doing it later in your flow?

**Comment by glancashire** [comment]
Yes, I validate and in the completion try to redeem in the completion handler...

**Comment by polok** [comment]
@glancashire Are you creating some view controller which you dismiss at some point in your flow? It looks, that `self` refers to is gone by the time the completion request handler gets executed and it's why it's nil. Please check out the below simple piece of code which works fine and more or less does what you are trying to achieve. 

```
client?.validations.validateVoucher(code: "polakos-voucher-1") { [weak self] (response) in
  
  guard let strongSelf = self else {
    return
  }
  
  strongSelf.client?.redemptions.redeem(code: "polakos-voucher-1") { [weak self] (response) in
    debugPrint(response ?? "")
  }
}
```
Please, if you could review your flow, as `self` shouldn't be nil, maybe OS kills it at some point in your flow when you didn't receive the response from `redem` call.

**Comment by glancashire** [comment]
@polok I admit that I have a complex flow.

I do this in a singleton function (so it should not really be released...)
And this has worked perfectly with you older SDK.

```
public func redeem(...) {
	let client = VoucherifyClient(clientId: VXLicenceManager.kVOUCHERIFY_CLIENTID, clientToken: VXLicenceManager.kVOUCHERIFY_CLIENTTOKEN , origin: origin, trackingId: self.identifier())
		
	client.validations.validateVoucher(code: voucherCode, orderItems: orderItems) { (validationResponse) in
		// check for success otherwise call completion with false return
		client.redemptions.redeem(code: voucherCode, redeemContext: redemptionContext) { (redemptionResponse) in
			// check for success and call completion with true otherwise return
		}
	}
}
```

**Comment by polok** [comment]
@glancashire Who/What actually invokes this `redeem` function?

Btw. What was the previous version of SDK which you were using?

**Comment by glancashire** [comment]
@polok 

The user opens a screen where he enters the voucher code. When he presses a button the redeem function on the singleton is called. The screen remains visible and waits for the completion handler to return.

Oh and we were very happy users of the Release v1.3.0 ;-)

**Comment by polok** [comment]
@glancashire Just for testing purposes. Could you declare the Voucherify's client outside your `redeem` function, maybe as VC field?

Btw. So you made a 'big' jump in versions ;)

**Comment by glancashire** [comment]
I have declared the client as a var on the singleton, now it seems to work.
why this is I have no logical conclusion ;-)
thanks for your help.

kind regards
graham
```
private var client:VoucherifyClient?

public func redeem(itemCode:String, voucherCode:String, email: String?, metadata: Dictionary<String, AnyObject>?, completion:@escaping (_ success: Bool) -> ())  {
	
	self.client = VoucherifyClient(clientId: VXLicenceManager.kVOUCHERIFY_CLIENTID, clientToken: VXLicenceManager.kVOUCHERIFY_CLIENTTOKEN , origin: "https://www.swift.ch", trackingId: self.identifier())
	// Validate voucher by its code
	self.client?.validations.validateVoucher(code: voucherCode, orderItems: orderItems) { (validationResponse) in
		self.client?.redemptions.redeem(code: voucherCode, redeemContext: redemptionContext) { (redemptionResponse) in
	
```

**Comment by polok** [comment]
@glancashire I believe that OS releases your client just after you get the response from Voucherify, because it was declared inside the method which actually ends when you receive the response but before you provide the response to UI.

Good to hear that it was resolved in that way. Also, don't hesitate to write in the future if something is not clear enough.
