### ISSUE TITLE
Alamofire 5.2

### ISSUE THREAD

**Issue by glancashire** [voucherifyio/voucherify-ios-sdk#34]
It would be cool if you could move to alamofire 5.2, as you are blocking me from using the new version ;-)

Kind Regards
Graham

**Comment by polok** [comment]
Hello @glancashire,

Excuse me for being so slow in responding! I have good and bad news. We are not moving to Alamofire 5.2, we are moving to 5.3 ;).

Please, check [this](https://github.com/voucherifyio/voucherify-ios-sdk/pull/36) PR.

**Comment by glancashire** [comment]
Thx, looking forward to the release

Kind Regards

Graham

**Comment by polok** [comment]
v4.1.0 has been just released
