### ISSUE TITLE
Configure your website URL in Client-side Settings.

### ISSUE THREAD

**Issue by kuldeep13990** [voucherifyio/voucherify-ios-sdk#9]
I am using ApplicationSandboxAppID and ApplicationSandboxAppSecret but while verifying coupon it will gives me error like below.

**FAILURE: GeneralError(code: Optional(403), details: Optional("Origin \'http://voucherify-swift\' is not trusted. Configure \'Your website URL\' in Client-side Settings."), message: Optional("Invalid origin"))**

How can I Fix this error?

**Comment by frakti** [comment]
Have you configured `voucherify-swift` as a trusted domain in your project settings?

**Comment by kuldeep13990** [comment]
yes I have configured it and now I am able to redeem voucher but I am not able to parse response data. I am able to see data but when try to get it in NSDictionary or VoucherRedemptionResult it raise BAD_ACCESS error.

How can I parse it?

**Comment by polok** [comment]
Could you check the response which you are getting in the logs?

**Comment by kuldeep13990** [comment]
I got the required response . Thanks for your help.
Now you can close this question

**Comment by polok** [comment]
Glad that we could help.
